# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chihab/Bureau/bourezgui_morandeau_risk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chihab/Bureau/bourezgui_morandeau_risk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chihab/Bureau/bourezgui_morandeau_risk/CMakeFiles /home/chihab/Bureau/bourezgui_morandeau_risk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chihab/Bureau/bourezgui_morandeau_risk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named Test

# Build rule for target.
Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test
.PHONY : Test

# fast build rule for target.
Test/fast:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/build
.PHONY : Test/fast

divers/Test.o: divers/Test.cpp.o
.PHONY : divers/Test.o

# target to build an object file
divers/Test.cpp.o:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/divers/Test.cpp.o
.PHONY : divers/Test.cpp.o

divers/Test.i: divers/Test.cpp.i
.PHONY : divers/Test.i

# target to preprocess a source file
divers/Test.cpp.i:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/divers/Test.cpp.i
.PHONY : divers/Test.cpp.i

divers/Test.s: divers/Test.cpp.s
.PHONY : divers/Test.s

# target to generate assembly for a file
divers/Test.cpp.s:
	$(MAKE) -f CMakeFiles/Test.dir/build.make CMakeFiles/Test.dir/divers/Test.cpp.s
.PHONY : divers/Test.cpp.s

src/Etat_jeu.o: src/Etat_jeu.cpp.o
.PHONY : src/Etat_jeu.o

# target to build an object file
src/Etat_jeu.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Etat_jeu.cpp.o
.PHONY : src/Etat_jeu.cpp.o

src/Etat_jeu.i: src/Etat_jeu.cpp.i
.PHONY : src/Etat_jeu.i

# target to preprocess a source file
src/Etat_jeu.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Etat_jeu.cpp.i
.PHONY : src/Etat_jeu.cpp.i

src/Etat_jeu.s: src/Etat_jeu.cpp.s
.PHONY : src/Etat_jeu.s

# target to generate assembly for a file
src/Etat_jeu.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Etat_jeu.cpp.s
.PHONY : src/Etat_jeu.cpp.s

src/Frontiere.o: src/Frontiere.cpp.o
.PHONY : src/Frontiere.o

# target to build an object file
src/Frontiere.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Frontiere.cpp.o
.PHONY : src/Frontiere.cpp.o

src/Frontiere.i: src/Frontiere.cpp.i
.PHONY : src/Frontiere.i

# target to preprocess a source file
src/Frontiere.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Frontiere.cpp.i
.PHONY : src/Frontiere.cpp.i

src/Frontiere.s: src/Frontiere.cpp.s
.PHONY : src/Frontiere.s

# target to generate assembly for a file
src/Frontiere.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Frontiere.cpp.s
.PHONY : src/Frontiere.cpp.s

src/IA_moyen.o: src/IA_moyen.cpp.o
.PHONY : src/IA_moyen.o

# target to build an object file
src/IA_moyen.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/IA_moyen.cpp.o
.PHONY : src/IA_moyen.cpp.o

src/IA_moyen.i: src/IA_moyen.cpp.i
.PHONY : src/IA_moyen.i

# target to preprocess a source file
src/IA_moyen.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/IA_moyen.cpp.i
.PHONY : src/IA_moyen.cpp.i

src/IA_moyen.s: src/IA_moyen.cpp.s
.PHONY : src/IA_moyen.s

# target to generate assembly for a file
src/IA_moyen.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/IA_moyen.cpp.s
.PHONY : src/IA_moyen.cpp.s

src/Ia.o: src/Ia.cpp.o
.PHONY : src/Ia.o

# target to build an object file
src/Ia.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Ia.cpp.o
.PHONY : src/Ia.cpp.o

src/Ia.i: src/Ia.cpp.i
.PHONY : src/Ia.i

# target to preprocess a source file
src/Ia.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Ia.cpp.i
.PHONY : src/Ia.cpp.i

src/Ia.s: src/Ia.cpp.s
.PHONY : src/Ia.s

# target to generate assembly for a file
src/Ia.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Ia.cpp.s
.PHONY : src/Ia.cpp.s

src/Joueur.o: src/Joueur.cpp.o
.PHONY : src/Joueur.o

# target to build an object file
src/Joueur.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Joueur.cpp.o
.PHONY : src/Joueur.cpp.o

src/Joueur.i: src/Joueur.cpp.i
.PHONY : src/Joueur.i

# target to preprocess a source file
src/Joueur.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Joueur.cpp.i
.PHONY : src/Joueur.cpp.i

src/Joueur.s: src/Joueur.cpp.s
.PHONY : src/Joueur.s

# target to generate assembly for a file
src/Joueur.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Joueur.cpp.s
.PHONY : src/Joueur.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Moteur_jeu.o: src/Moteur_jeu.cpp.o
.PHONY : src/Moteur_jeu.o

# target to build an object file
src/Moteur_jeu.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Moteur_jeu.cpp.o
.PHONY : src/Moteur_jeu.cpp.o

src/Moteur_jeu.i: src/Moteur_jeu.cpp.i
.PHONY : src/Moteur_jeu.i

# target to preprocess a source file
src/Moteur_jeu.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Moteur_jeu.cpp.i
.PHONY : src/Moteur_jeu.cpp.i

src/Moteur_jeu.s: src/Moteur_jeu.cpp.s
.PHONY : src/Moteur_jeu.s

# target to generate assembly for a file
src/Moteur_jeu.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Moteur_jeu.cpp.s
.PHONY : src/Moteur_jeu.cpp.s

src/Pion.o: src/Pion.cpp.o
.PHONY : src/Pion.o

# target to build an object file
src/Pion.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Pion.cpp.o
.PHONY : src/Pion.cpp.o

src/Pion.i: src/Pion.cpp.i
.PHONY : src/Pion.i

# target to preprocess a source file
src/Pion.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Pion.cpp.i
.PHONY : src/Pion.cpp.i

src/Pion.s: src/Pion.cpp.s
.PHONY : src/Pion.s

# target to generate assembly for a file
src/Pion.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Pion.cpp.s
.PHONY : src/Pion.cpp.s

src/Territoire.o: src/Territoire.cpp.o
.PHONY : src/Territoire.o

# target to build an object file
src/Territoire.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Territoire.cpp.o
.PHONY : src/Territoire.cpp.o

src/Territoire.i: src/Territoire.cpp.i
.PHONY : src/Territoire.i

# target to preprocess a source file
src/Territoire.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Territoire.cpp.i
.PHONY : src/Territoire.cpp.i

src/Territoire.s: src/Territoire.cpp.s
.PHONY : src/Territoire.s

# target to generate assembly for a file
src/Territoire.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Territoire.cpp.s
.PHONY : src/Territoire.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Main"
	@echo "... Test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... divers/Test.o"
	@echo "... divers/Test.i"
	@echo "... divers/Test.s"
	@echo "... src/Etat_jeu.o"
	@echo "... src/Etat_jeu.i"
	@echo "... src/Etat_jeu.s"
	@echo "... src/Frontiere.o"
	@echo "... src/Frontiere.i"
	@echo "... src/Frontiere.s"
	@echo "... src/IA_moyen.o"
	@echo "... src/IA_moyen.i"
	@echo "... src/IA_moyen.s"
	@echo "... src/Ia.o"
	@echo "... src/Ia.i"
	@echo "... src/Ia.s"
	@echo "... src/Joueur.o"
	@echo "... src/Joueur.i"
	@echo "... src/Joueur.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Moteur_jeu.o"
	@echo "... src/Moteur_jeu.i"
	@echo "... src/Moteur_jeu.s"
	@echo "... src/Pion.o"
	@echo "... src/Pion.i"
	@echo "... src/Pion.s"
	@echo "... src/Territoire.o"
	@echo "... src/Territoire.i"
	@echo "... src/Territoire.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

